export const COUNTRY_CODES = [
  { value: "+93", label: "Afghanistan (+93)" },
  { value: "+355", label: "Albania (+355)" },
  { value: "+213", label: "Algeria (+213)" },
  { value: "+1-684", label: "American Samoa (+1-684)" },
  { value: "+376", label: "Andorra (+376)" },
  { value: "+244", label: "Angola (+244)" },
  { value: "+1-264", label: "Anguilla (+1-264)" },
  { value: "+672", label: "Antarctica (+672)" },
  { value: "+1-268", label: "Antigua and Barbuda (+1-268)" },
  { value: "+54", label: "Argentina (+54)" },
  { value: "+374", label: "Armenia (+374)" },
  { value: "+297", label: "Aruba (+297)" },
  { value: "+61", label: "Australia (+61)" },
  { value: "+43", label: "Austria (+43)" },
  { value: "+994", label: "Azerbaijan (+994)" },
  { value: "+1-242", label: "Bahamas (+1-242)" },
  { value: "+973", label: "Bahrain (+973)" },
  { value: "+880", label: "Bangladesh (+880)" },
  { value: "+1-246", label: "Barbados (+1-246)" },
  { value: "+375", label: "Belarus (+375)" },
  { value: "+32", label: "Belgium (+32)" },
  { value: "+501", label: "Belize (+501)" },
  { value: "+229", label: "Benin (+229)" },
  { value: "+1-441", label: "Bermuda (+1-441)" },
  { value: "+975", label: "Bhutan (+975)" },
  { value: "+591", label: "Bolivia (+591)" },
  { value: "+387", label: "Bosnia and Herzegovina (+387)" },
  { value: "+267", label: "Botswana (+267)" },
  { value: "+55", label: "Brazil (+55)" },
  { value: "+246", label: "British Indian Ocean Territory (+246)" },
  { value: "+1-284", label: "British Virgin Islands (+1-284)" },
  { value: "+673", label: "Brunei (+673)" },
  { value: "+359", label: "Bulgaria (+359)" },
  { value: "+226", label: "Burkina Faso (+226)" },
  { value: "+257", label: "Burundi (+257)" },
  { value: "+855", label: "Cambodia (+855)" },
  { value: "+237", label: "Cameroon (+237)" },
  { value: "+1", label: "Canada (+1)" },
  { value: "+238", label: "Cape Verde (+238)" },
  { value: "+1-345", label: "Cayman Islands (+1-345)" },
  { value: "+236", label: "Central African Republic (+236)" },
  { value: "+235", label: "Chad (+235)" },
  { value: "+56", label: "Chile (+56)" },
  { value: "+86", label: "China (+86)" },
  { value: "+61", label: "Christmas Island (+61)" },
  { value: "+61", label: "Cocos Islands (+61)" },
  { value: "+57", label: "Colombia (+57)" },
  { value: "+269", label: "Comoros (+269)" },
  { value: "+682", label: "Cook Islands (+682)" },
  { value: "+506", label: "Costa Rica (+506)" },
  { value: "+385", label: "Croatia (+385)" },
  { value: "+53", label: "Cuba (+53)" },
  { value: "+599", label: "Curacao (+599)" },
  { value: "+357", label: "Cyprus (+357)" },
  { value: "+420", label: "Czech Republic (+420)" },
  { value: "+243", label: "Democratic Republic of the Congo (+243)" },
  { value: "+45", label: "Denmark (+45)" },
  { value: "+253", label: "Djibouti (+253)" },
  { value: "+1-767", label: "Dominica (+1-767)" },
  { value: "+1-809", label: "Dominican Republic (+1-809)" },
  { value: "+593", label: "Ecuador (+593)" },
  { value: "+20", label: "Egypt (+20)" },
  { value: "+503", label: "El Salvador (+503)" },
  { value: "+240", label: "Equatorial Guinea (+240)" },
  { value: "+291", label: "Eritrea (+291)" },
  { value: "+372", label: "Estonia (+372)" },
  { value: "+251", label: "Ethiopia (+251)" },
  { value: "+500", label: "Falkland Islands (+500)" },
  { value: "+298", label: "Faroe Islands (+298)" },
  { value: "+679", label: "Fiji (+679)" },
  { value: "+358", label: "Finland (+358)" },
  { value: "+33", label: "France (+33)" },
  { value: "+594", label: "French Guiana (+594)" },
  { value: "+689", label: "French Polynesia (+689)" },
  { value: "+241", label: "Gabon (+241)" },
  { value: "+220", label: "Gambia (+220)" },
  { value: "+995", label: "Georgia (+995)" },
  { value: "+49", label: "Germany (+49)" },
  { value: "+233", label: "Ghana (+233)" },
  { value: "+350", label: "Gibraltar (+350)" },
  { value: "+30", label: "Greece (+30)" },
  { value: "+299", label: "Greenland (+299)" },
  { value: "+1-473", label: "Grenada (+1-473)" },
  { value: "+590", label: "Guadeloupe (+590)" },
  { value: "+1-671", label: "Guam (+1-671)" },
  { value: "+502", label: "Guatemala (+502)" },
  { value: "+224", label: "Guinea (+224)" },
  { value: "+245", label: "Guinea-Bissau (+245)" },
  { value: "+592", label: "Guyana (+592)" },
  { value: "+509", label: "Haiti (+509)" },
  { value: "+504", label: "Honduras (+504)" },
  { value: "+852", label: "Hong Kong (+852)" },
  { value: "+36", label: "Hungary (+36)" },
  { value: "+354", label: "Iceland (+354)" },
  { value: "+91", label: "India (+91)" },
  { value: "+62", label: "Indonesia (+62)" },
  { value: "+98", label: "Iran (+98)" },
  { value: "+964", label: "Iraq (+964)" },
  { value: "+353", label: "Ireland (+353)" },
  { value: "+972", label: "Israel (+972)" },
  { value: "+39", label: "Italy (+39)" },
  { value: "+1-876", label: "Jamaica (+1-876)" },
  { value: "+81", label: "Japan (+81)" },
  { value: "+962", label: "Jordan (+962)" },
  { value: "+7", label: "Kazakhstan (+7)" },
  { value: "+254", label: "Kenya (+254)" },
  // ... you can continue for all countries.
];

export const COUNTRY_NAMES = [
  { value: "aw", label: "Aruba" },
  { value: "af", label: "Afghanistan" },
  { value: "ao", label: "Angola" },
  { value: "ai", label: "Anguilla" },
  { value: "ax", label: "Åland Islands" },
  { value: "al", label: "Albania" },
  { value: "ad", label: "Andorra" },
  { value: "ae", label: "United Arab Emirates" },
  { value: "ar", label: "Argentina" },
  { value: "am", label: "Armenia" },
  { value: "as", label: "American Samoa" },
  { value: "aq", label: "Antarctica" },
  { value: "tf", label: "French Southern Territories" },
  { value: "ag", label: "Antigua and Barbuda" },
  { value: "au", label: "Australia" },
  { value: "at", label: "Austria" },
  { value: "az", label: "Azerbaijan" },
  { value: "bi", label: "Burundi" },
  { value: "be", label: "Belgium" },
  { value: "bj", label: "Benin" },
  { value: "bq", label: "Bonaire, Sint Eustatius and Saba" },
  { value: "bf", label: "Burkina Faso" },
  { value: "bd", label: "Bangladesh" },
  { value: "bg", label: "Bulgaria" },
  { value: "bh", label: "Bahrain" },
  { value: "bs", label: "Bahamas" },
  { value: "ba", label: "Bosnia and Herzegovina" },
  { value: "bl", label: "Saint Barthélemy" },
  { value: "by", label: "Belarus" },
  { value: "bz", label: "Belize" },
  { value: "bm", label: "Bermuda" },
  { value: "bo", label: "Bolivia, Plurinational State of" },
  { value: "br", label: "Brazil" },
  { value: "bb", label: "Barbados" },
  { value: "bn", label: "Brunei Darussalam" },
  { value: "bt", label: "Bhutan" },
  { value: "bv", label: "Bouvet Island" },
  { value: "bw", label: "Botswana" },
  { value: "cf", label: "Central African Republic" },
  { value: "ca", label: "Canada" },
  { value: "cc", label: "Cocos (Keeling) Islands" },
  { value: "ch", label: "Switzerland" },
  { value: "cl", label: "Chile" },
  { value: "cn", label: "China" },
  { value: "ci", label: "Côte d'Ivoire" },
  { value: "cm", label: "Cameroon" },
  { value: "cd", label: "Congo, The Democratic Republic of the" },
  { value: "cg", label: "Congo" },
  { value: "ck", label: "Cook Islands" },
  { value: "co", label: "Colombia" },
  { value: "km", label: "Comoros" },
  { value: "cv", label: "Cabo Verde" },
  { value: "cr", label: "Costa Rica" },
  { value: "cu", label: "Cuba" },
  { value: "cw", label: "Curaçao" },
  { value: "cx", label: "Christmas Island" },
  { value: "ky", label: "Cayman Islands" },
  { value: "cy", label: "Cyprus" },
  { value: "cz", label: "Czechia" },
  { value: "de", label: "Germany" },
  { value: "dj", label: "Djibouti" },
  { value: "dm", label: "Dominica" },
  { value: "dk", label: "Denmark" },
  { value: "do", label: "Dominican Republic" },
  { value: "dz", label: "Algeria" },
  { value: "ec", label: "Ecuador" },
  { value: "eg", label: "Egypt" },
  { value: "er", label: "Eritrea" },
  { value: "eh", label: "Western Sahara" },
  { value: "es", label: "Spain" },
  { value: "ee", label: "Estonia" },
  { value: "et", label: "Ethiopia" },
  { value: "fi", label: "Finland" },
  { value: "fj", label: "Fiji" },
  { value: "fk", label: "Falkland Islands (Malvinas)" },
  { value: "fr", label: "France" },
  { value: "fo", label: "Faroe Islands" },
  { value: "fm", label: "Micronesia, Federated States of" },
  { value: "ga", label: "Gabon" },
  { value: "gb", label: "United Kingdom" },
  { value: "ge", label: "Georgia" },
  { value: "gg", label: "Guernsey" },
  { value: "gh", label: "Ghana" },
  { value: "gi", label: "Gibraltar" },
  { value: "gn", label: "Guinea" },
  { value: "gp", label: "Guadeloupe" },
  { value: "gm", label: "Gambia" },
  { value: "gw", label: "Guinea-Bissau" },
  { value: "gq", label: "Equatorial Guinea" },
  { value: "gr", label: "Greece" },
  { value: "gd", label: "Grenada" },
  { value: "gl", label: "Greenland" },
  { value: "gt", label: "Guatemala" },
  { value: "gf", label: "French Guiana" },
  { value: "gu", label: "Guam" },
  { value: "gy", label: "Guyana" },
  { value: "hk", label: "Hong Kong" },
  { value: "hm", label: "Heard Island and McDonald Islands" },
  { value: "hn", label: "Honduras" },
  { value: "hr", label: "Croatia" },
  { value: "ht", label: "Haiti" },
  { value: "hu", label: "Hungary" },
  { value: "id", label: "Indonesia" },
  { value: "im", label: "Isle of Man" },
  { value: "in", label: "India" },
  { value: "io", label: "British Indian Ocean Territory" },
  { value: "ie", label: "Ireland" },
  { value: "ir", label: "Iran, Islamic Republic of" },
  { value: "iq", label: "Iraq" },
  { value: "is", label: "Iceland" },
  { value: "il", label: "Israel" },
  { value: "it", label: "Italy" },
  { value: "jm", label: "Jamaica" },
  { value: "je", label: "Jersey" },
  { value: "jo", label: "Jordan" },
  { value: "jp", label: "Japan" },
  { value: "kz", label: "Kazakhstan" },
  { value: "ke", label: "Kenya" },
  { value: "kg", label: "Kyrgyzstan" },
  { value: "kh", label: "Cambodia" },
  { value: "ki", label: "Kiribati" },
  { value: "kn", label: "Saint Kitts and Nevis" },
  { value: "kr", label: "Korea, Republic of" },
  { value: "kw", label: "Kuwait" },
  { value: "la", label: "Lao People's Democratic Republic" },
  { value: "lb", label: "Lebanon" },
  { value: "lr", label: "Liberia" },
  { value: "ly", label: "Libya" },
  { value: "lc", label: "Saint Lucia" },
  { value: "li", label: "Liechtenstein" },
  { value: "lk", label: "Sri Lanka" },
  { value: "ls", label: "Lesotho" },
  { value: "lt", label: "Lithuania" },
  { value: "lu", label: "Luxembourg" },
  { value: "lv", label: "Latvia" },
  { value: "mo", label: "Macao" },
  { value: "mf", label: "Saint Martin (French part)" },
  { value: "ma", label: "Morocco" },
  { value: "mc", label: "Monaco" },
  { value: "md", label: "Moldova, Republic of" },
  { value: "mg", label: "Madagascar" },
  { value: "mv", label: "Maldives" },
  { value: "mx", label: "Mexico" },
  { value: "mh", label: "Marshall Islands" },
  { value: "mk", label: "North Macedonia" },
  { value: "ml", label: "Mali" },
  { value: "mt", label: "Malta" },
  { value: "mm", label: "Myanmar" },
  { value: "me", label: "Montenegro" },
  { value: "mn", label: "Mongolia" },
  { value: "mp", label: "Northern Mariana Islands" },
  { value: "mz", label: "Mozambique" },
  { value: "mr", label: "Mauritania" },
  { value: "ms", label: "Montserrat" },
  { value: "mq", label: "Martinique" },
  { value: "mu", label: "Mauritius" },
  { value: "mw", label: "Malawi" },
  { value: "my", label: "Malaysia" },
  { value: "yt", label: "Mayotte" },
  { value: "na", label: "Namibia" },
  { value: "nc", label: "New Caledonia" },
  { value: "ne", label: "Niger" },
  { value: "nf", label: "Norfolk Island" },
  { value: "ng", label: "Nigeria" },
  { value: "ni", label: "Nicaragua" },
  { value: "nu", label: "Niue" },
  { value: "nl", label: "Netherlands" },
  { value: "no", label: "Norway" },
  { value: "np", label: "Nepal" },
  { value: "nr", label: "Nauru" },
  { value: "nz", label: "New Zealand" },
  { value: "om", label: "Oman" },
  { value: "pk", label: "Pakistan" },
  { value: "pa", label: "Panama" },
  { value: "pn", label: "Pitcairn" },
  { value: "pe", label: "Peru" },
  { value: "ph", label: "Philippines" },
  { value: "pw", label: "Palau" },
  { value: "pg", label: "Papua New Guinea" },
  { value: "pl", label: "Poland" },
  { value: "pr", label: "Puerto Rico" },
  { value: "kp", label: "Korea, Democratic People's Republic of" },
  { value: "pt", label: "Portugal" },
  { value: "py", label: "Paraguay" },
  { value: "ps", label: "Palestine, State of" },
  { value: "pf", label: "French Polynesia" },
  { value: "qa", label: "Qatar" },
  { value: "re", label: "Réunion" },
  { value: "ro", label: "Romania" },
  { value: "ru", label: "Russian Federation" },
  { value: "rw", label: "Rwanda" },
  { value: "sa", label: "Saudi Arabia" },
  { value: "sd", label: "Sudan" },
  { value: "sn", label: "Senegal" },
  { value: "sg", label: "Singapore" },
  { value: "gs", label: "South Georgia and the South Sandwich Islands" },
  { value: "sh", label: "Saint Helena, Ascension and Tristan da Cunha" },
  { value: "sj", label: "Svalbard and Jan Mayen" },
  { value: "sb", label: "Solomon Islands" },
  { value: "sl", label: "Sierra Leone" },
  { value: "sv", label: "El Salvador" },
  { value: "sm", label: "San Marino" },
  { value: "so", label: "Somalia" },
  { value: "pm", label: "Saint Pierre and Miquelon" },
  { value: "rs", label: "Serbia" },
  { value: "ss", label: "South Sudan" },
  { value: "st", label: "Sao Tome and Principe" },
  { value: "sr", label: "Suriname" },
  { value: "sk", label: "Slovakia" },
  { value: "si", label: "Slovenia" },
  { value: "se", label: "Sweden" },
  { value: "sz", label: "Eswatini" },
  { value: "sx", label: "Sint Maarten (Dutch part)" },
  { value: "sc", label: "Seychelles" },
  { value: "sy", label: "Syrian Arab Republic" },
  { value: "tc", label: "Turks and Caicos Islands" },
  { value: "td", label: "Chad" },
  { value: "tg", label: "Togo" },
  { value: "th", label: "Thailand" },
  { value: "tj", label: "Tajikistan" },
  { value: "tk", label: "Tokelau" },
  { value: "tm", label: "Turkmenistan" },
  { value: "tl", label: "Timor-Leste" },
  { value: "to", label: "Tonga" },
  { value: "tt", label: "Trinidad and Tobago" },
  { value: "tn", label: "Tunisia" },
  { value: "tr", label: "Turkey" },
  { value: "tv", label: "Tuvalu" },
  { value: "tw", label: "Taiwan, Province of China" },
  { value: "tz", label: "Tanzania, United Republic of" },
  { value: "ug", label: "Uganda" },
  { value: "ua", label: "Ukraine" },
  { value: "um", label: "United States Minor Outlying Islands" },
  { value: "uy", label: "Uruguay" },
  { value: "us", label: "United States" },
  { value: "uz", label: "Uzbekistan" },
  { value: "va", label: "Holy See (Vatican City State)" },
  { value: "vc", label: "Saint Vincent and the Grenadines" },
  { value: "ve", label: "Venezuela, Bolivarian Republic of" },
  { value: "vg", label: "Virgin Islands, British" },
  { value: "vi", label: "Virgin Islands, U.S." },
  { value: "vn", label: "Viet Nam" },
  { value: "vu", label: "Vanuatu" },
  { value: "wf", label: "Wallis and Futuna" },
  { value: "ws", label: "Samoa" },
  { value: "ye", label: "Yemen" },
  { value: "za", label: "South Africa" },
  { value: "zm", label: "Zambia" },
  { value: "zw", label: "Zimbabwe" },
];
