export const predefinedKeywords = [
  // Competitions
  "Premier League",
  "Championship",
  "FA Cup",
  "EFL Cup",
  "Community Shield",
  "Europa League",
  "Champions League",
  "Conference League",

  // Top Premier League Clubs
  "Liverpool",
  "Manchester City",
  "Manchester United",
  "Chelsea",
  "Arsenal",
  "Tottenham Hotspur",
  "Newcastle United",
  "Aston Villa",
  "West Ham United",
  "Everton",
  "Crystal Palace",
  "Brighton",
  "Brentford",
  "Fulham",
  "Wolverhampton Wanderers",
  "Nottingham Forest",
  "Bournemouth",
  "Burnley",
  "Sheffield United",
  "Luton Town",
  "Sunderland",

  // Championship Clubs
  "Leeds United",
  "Leicester City",
  "Southampton",
  "Norwich City",
  "West Bromwich Albion",
  "Hull City",
  "Middlesbrough",
  "Stoke City",

  // Popular European Clubs
  "Real Madrid",
  "Barcelona",
  "Atletico Madrid",
  "Bayern Munich",
  "Borussia Dortmund",
  "Paris Saint-Germain",
  "AC Milan",
  "Inter Milan",
  "Juventus",
  "Napoli",
  "Ajax",

  // Famous Stadiums
  "Anfield",
  "Etihad Stadium",
  "Old Trafford",
  "Stamford Bridge",
  "Emirates Stadium",
  "Tottenham Hotspur Stadium",
  "Goodison Park",
  "Villa Park",
  "London Stadium",
  "Selhurst Park",
  "Elland Road",
  "King Power Stadium",
  "St. Mary's Stadium",
  "Carrow Road",
  "Bramall Lane",
  "Turf Moor",
  "Vitality Stadium",

  // Cities or regional references
  // "London",
  // "Manchester",
  // "Liverpool",
  // "Birmingham",
  // "Leeds",
  // "Southampton",
  // "Leicester",
  // "Newcastle",
  // "Sheffield",
];

export const teamRedirects: Record<string, string> = {
  // Teams
  Liverpool: "Liverpool",
  "Manchester City": "Manchester City",
  "Manchester United": "Manchester United",
  Chelsea: "Chelsea",
  Arsenal: "Arsenal",
  "Tottenham Hotspur": "Tottenham Hotspur",
  "Newcastle United": "Newcastle United",
  "Aston Villa": "Aston Villa",
  "West Ham United": "West Ham United",
  Everton: "Everton",
  "Crystal Palace": "Crystal Palace",
  Brighton: "Brighton",
  Brentford: "Brentford",
  Fulham: "Fulham",
  "Wolverhampton Wanderers": "Wolverhampton Wanderers",
  "Nottingham Forest": "Nottingham Forest",
  Bournemouth: "Bournemouth",
  Burnley: "Burnley",
  "Sheffield United": "Sheffield United",
  "Luton Town": "Luton Town",
  Sunderland: "Sunderland",

  // Stadiums
  Anfield: "Liverpool",
  "Etihad Stadium": "Manchester City",
  "Old Trafford": "Manchester United",
  "Stamford Bridge": "Chelsea",
  "Emirates Stadium": "Arsenal",
  "Tottenham Hotspur Stadium": "Tottenham Hotspur",
  "Goodison Park": "Everton",
  "Villa Park": "Aston Villa",
  "London Stadium": "West Ham United",
  "Selhurst Park": "Crystal Palace",
  "Elland Road": "Leeds United", // Optional, if not needed, remove
  "King Power Stadium": "Leicester City",
  "St. Mary's Stadium": "Southampton",
  "Carrow Road": "Norwich City",
  "Bramall Lane": "Sheffield United",
  "Turf Moor": "Burnley",
  "Vitality Stadium": "Bournemouth",
};

export const leagueRedirects: Record<string, string> = {
  // Leagues

  "Premier League": "Premier League",
  Championship: "Championship",
  "FA Cup": "FA Cup",
  "EFL Cup": "EFL Cup",
  "Community Shield": "Community Shield",
  "Europa League": "Europa League",
  "Champions League": "Champions League",
  "Conference League": "Conference League",
};
