export const premier_league_2025_2026_events = [
    {
        homeTeam: "Manchester United",
        id: 1,
        categoryName: "Premier League",
        eventName: "Manchester United vs Tottenham Hotspur",
        year: 2025,
        month: "August",
        day: 10,
        venue: "Old Trafford",
        city: "Manchester",
        country: "England",
        time: "15:00",
        urlToEvent: "https://example.com/match/1",
        tba: false,
        minPrice: { gbp: 95, usd: 120, eur: 110, aud: 170, cad: 160, chf: 105 },
    },
    {
        homeTeam: "Arsenal",
        id: 2,
        categoryName: "Premier League",
        eventName: "Arsenal vs Newcastle United",
        year: 2025,
        month: "August",
        day: 16,
        venue: "Emirates Stadium",
        city: "London",
        country: "England",
        time: "17:30",
        urlToEvent: "https://example.com/match/2",
        tba: false,
        minPrice: { gbp: 105, usd: 130, eur: 120, aud: 185, cad: 175, chf: 115 },
    },
    {
        homeTeam: "Chelsea",
        id: 3,
        categoryName: "Premier League",
        eventName: "Chelsea vs Liverpool",
        year: 2025,
        month: "August",
        day: 17,
        venue: "Stamford Bridge",
        city: "London",
        country: "England",
        time: "16:00",
        urlToEvent: "https://example.com/match/3",
        tba: false,
        minPrice: { gbp: 110, usd: 140, eur: 130, aud: 200, cad: 190, chf: 120 },
    },
    {
        homeTeam: "Liverpool",
        id: 4,
        categoryName: "Premier League",
        eventName: "Liverpool vs Everton",
        year: 2025,
        month: "August",
        day: 23,
        venue: "Anfield",
        city: "Liverpool",
        country: "England",
        time: "12:30",
        urlToEvent: "https://example.com/match/4",
        tba: false,
        minPrice: { gbp: 100, usd: 125, eur: 115, aud: 180, cad: 170, chf: 110 },
    },
    {
        homeTeam: "Manchester City",
        id: 5,
        categoryName: "Premier League",
        eventName: "Manchester City vs West Ham United",
        year: 2025,
        month: "August",
        day: 24,
        venue: "Etihad Stadium",
        city: "Manchester",
        country: "England",
        time: "14:00",
        urlToEvent: "https://example.com/match/5",
        tba: false,
        minPrice: { gbp: 90, usd: 115, eur: 105, aud: 165, cad: 155, chf: 100 },
    },
    {
        homeTeam: "Aston Villa",
        id: 6,
        categoryName: "Premier League",
        eventName: "Aston Villa vs Fulham",
        year: 2025,
        month: "August",
        day: 30,
        venue: "Villa Park",
        city: "Birmingham",
        country: "England",
        time: "15:00",
        urlToEvent: "https://example.com/match/6",
        tba: false,
        minPrice: { gbp: 75, usd: 95, eur: 85, aud: 135, cad: 125, chf: 80 },
    },
    {
        homeTeam: "Brighton & Hove Albion",
        id: 7,
        categoryName: "Premier League",
        eventName: "Brighton & Hove Albion vs Crystal Palace",
        year: 2025,
        month: "August",
        day: 31,
        venue: "Falmer Stadium",
        city: "Brighton",
        country: "England",
        time: "14:00",
        urlToEvent: "https://example.com/match/7",
        tba: false,
        minPrice: { gbp: 70, usd: 90, eur: 80, aud: 130, cad: 120, chf: 75 },
    },
    {
        homeTeam: "Tottenham Hotspur",
        id: 8,
        categoryName: "Premier League",
        eventName: "Tottenham Hotspur vs Manchester United",
        year: 2025,
        month: "September",
        day: 6,
        venue: "Tottenham Hotspur Stadium",
        city: "London",
        country: "England",
        time: "17:30",
        urlToEvent: "https://example.com/match/8",
        tba: false,
        minPrice: { gbp: 115, usd: 145, eur: 135, aud: 210, cad: 200, chf: 125 },
    },
    {
        homeTeam: "Newcastle United",
        id: 9,
        categoryName: "Premier League",
        eventName: "Newcastle United vs Arsenal",
        year: 2025,
        month: "September",
        day: 7,
        venue: "St. James' Park",
        city: "Newcastle upon Tyne",
        country: "England",
        time: "16:00",
        urlToEvent: "https://example.com/match/9",
        tba: false,
        minPrice: { gbp: 100, usd: 125, eur: 115, aud: 180, cad: 170, chf: 110 },
    },
    {
        homeTeam: "Everton",
        id: 10,
        categoryName: "Premier League",
        eventName: "Everton vs Manchester City",
        year: 2025,
        month: "September",
        day: 13,
        venue: "Goodison Park",
        city: "Liverpool",
        country: "England",
        time: "15:00",
        urlToEvent: "https://example.com/match/10",
        tba: false,
        minPrice: { gbp: 80, usd: 100, eur: 90, aud: 145, cad: 135, chf: 85 },
    },
    {
        homeTeam: "West Ham United",
        id: 11,
        categoryName: "Premier League",
        eventName: "West Ham United vs Chelsea",
        year: 2025,
        month: "September",
        day: 14,
        venue: "London Stadium",
        city: "London",
        country: "England",
        time: "14:00",
        urlToEvent: "https://example.com/match/11",
        tba: false,
        minPrice: { gbp: 85, usd: 110, eur: 100, aud: 160, cad: 150, chf: 95 },
    },
    {
        homeTeam: "Crystal Palace",
        id: 12,
        categoryName: "Premier League",
        eventName: "Crystal Palace vs Aston Villa",
        year: 2025,
        month: "September",
        day: 20,
        venue: "Selhurst Park",
        city: "London",
        country: "England",
        time: "15:00",
        urlToEvent: "https://example.com/match/12",
        tba: false,
        minPrice: { gbp: 70, usd: 90, eur: 80, aud: 130, cad: 120, chf: 75 },
    },
    {
        homeTeam: "Fulham",
        id: 13,
        categoryName: "Premier League",
        eventName: "Fulham vs Brighton & Hove Albion",
        year: 2025,
        month: "September",
        day: 21,
        venue: "Craven Cottage",
        city: "London",
        country: "England",
        time: "14:00",
        urlToEvent: "https://example.com/match/13",
        tba: false,
        minPrice: { gbp: 65, usd: 85, eur: 75, aud: 125, cad: 115, chf: 70 },
    },
    {
        homeTeam: "Leicester City",
        id: 14,
        categoryName: "Premier League",
        eventName: "Leicester City vs Manchester United",
        year: 2025,
        month: "September",
        day: 27,
        venue: "King Power Stadium",
        city: "Leicester",
        country: "England",
        time: "15:00",
        urlToEvent: "https://example.com/match/14",
        tba: false,
        minPrice: { gbp: 75, usd: 95, eur: 85, aud: 135, cad: 125, chf: 80 },
    },
    {
        homeTeam: "Leeds United",
        id: 15,
        categoryName: "Premier League",
        eventName: "Leeds United vs Arsenal",
        year: 2025,
        month: "September",
        day: 28,
        venue: "Elland Road",
        city: "Leeds",
        country: "England",
        time: "14:00",
        urlToEvent: "https://example.com/match/15",
        tba: false,
        minPrice: { gbp: 80, usd: 100, eur: 90, aud: 145, cad: 135, chf: 85 },
    },
    {
        homeTeam: "Southampton",
        id: 16,
        categoryName: "Premier League",
        eventName: "Southampton vs Chelsea",
        year: 2025,
        month: "October",
        day: 4,
        venue: "St Mary's Stadium",
        city: "Southampton",
        country: "England",
        time: "15:00",
        urlToEvent: "https://example.com/match/16",
        tba: false,
        minPrice: { gbp: 60, usd: 75, eur: 70, aud: 110, cad: 100, chf: 65 },
    },
    {
        homeTeam: "Wolves",
        id: 17,
        categoryName: "Premier League",
        eventName: "Wolves vs Liverpool",
        year: 2025,
        month: "October",
        day: 5,
        venue: "Molineux Stadium",
        city: "Wolverhampton",
        country: "England",
        time: "14:00",
        urlToEvent: "https://example.com/match/17",
        tba: false,
        minPrice: { gbp: 70, usd: 90, eur: 80, aud: 130, cad: 120, chf: 75 },
    },
    {
        homeTeam: "Burnley",
        id: 18,
        categoryName: "Premier League",
        eventName: "Burnley vs Manchester City",
        year: 2025,
        month: "October",
        day: 11,
        venue: "Turf Moor",
        city: "Burnley",
        country: "England",
        time: "15:00",
        urlToEvent: "https://example.com/match/18",
        tba: false,
        minPrice: { gbp: 60, usd: 75, eur: 70, aud: 110, cad: 100, chf: 65 },
    },
    {
        homeTeam: "Nottingham Forest",
        id: 19,
        categoryName: "Premier League",
        eventName: "Nottingham Forest vs Tottenham Hotspur",
        year: 2025,
        month: "October",
        day: 12,
        venue: "The City Ground",
        city: "Nottingham",
        country: "England",
        time: "14:00",
        urlToEvent: "https://example.com/match/19",
        tba: false,
        minPrice: { gbp: 65, usd: 85, eur: 75, aud: 125, cad: 115, chf: 70 },
    },
    {
        homeTeam: "Manchester United",
        id: 21,
        categoryName: "Premier League",
        eventName: "Manchester United vs Aston Villa",
        year: 2025,
        month: "October",
        day: 19,
        venue: "Old Trafford",
        city: "Manchester",
        country: "England",
        time: "16:00",
        urlToEvent: "https://example.com/match/21",
        tba: false,
        minPrice: { gbp: 90, usd: 115, eur: 105, aud: 165, cad: 155, chf: 100 },
    },
    {
        homeTeam: "Arsenal",
        id: 22,
        categoryName: "Premier League",
        eventName: "Arsenal vs Fulham",
        year: 2025,
        month: "October",
        day: 25,
        venue: "Emirates Stadium",
        city: "London",
        country: "England",
        time: "15:00",
        urlToEvent: "https://example.com/match/22",
        tba: false,
        minPrice: { gbp: 85, usd: 110, eur: 100, aud: 160, cad: 150, chf: 95 },
    },
    {
        homeTeam: "Chelsea",
        id: 23,
        categoryName: "Premier League",
        eventName: "Chelsea vs Crystal Palace",
        year: 2025,
        month: "October",
        day: 26,
        venue: "Stamford Bridge",
        city: "London",
        country: "England",
        time: "14:00",
        urlToEvent: "https://example.com/match/23",
        tba: false,
        minPrice: { gbp: 90, usd: 115, eur: 105, aud: 165, cad: 155, chf: 100 },
    },
    {
        homeTeam: "Liverpool",
        id: 24,
        categoryName: "Premier League",
        eventName: "Liverpool vs Brighton & Hove Albion",
        year: 2025,
        month: "November",
        day: 1,
        venue: "Anfield",
        city: "Liverpool",
        country: "England",
        time: "15:00",
        urlToEvent: "https://example.com/match/24",
        tba: false,
        minPrice: { gbp: 95, usd: 120, eur: 110, aud: 170, cad: 160, chf: 105 },
    },
    {
        homeTeam: "Manchester City",
        id: 25,
        categoryName: "Premier League",
        eventName: "Manchester City vs Leicester City",
        year: 2025,
        month: "November",
        day: 2,
        venue: "Etihad Stadium",
        city: "Manchester",
        country: "England",
        time: "14:00",
        urlToEvent: "https://example.com/match/25",
        tba: false,
        minPrice: { gbp: 80, usd: 100, eur: 90, aud: 145, cad: 135, chf: 85 },
    },
    {
        homeTeam: "Tottenham Hotspur",
        id: 26,
        categoryName: "Premier League",
        eventName: "Tottenham Hotspur vs Leeds United",
        year: 2025,
        month: "November",
        day: 8,
        venue: "Tottenham Hotspur Stadium",
        city: "London",
        country: "England",
        time: "15:00",
        urlToEvent: "https://example.com/match/26",
        tba: false,
        minPrice: { gbp: 100, usd: 125, eur: 115, aud: 180, cad: 170, chf: 110 },
    },
    {
        homeTeam: "Newcastle United",
        id: 27,
        categoryName: "Premier League",
        eventName: "Newcastle United vs Southampton",
        year: 2025,
        month: "November",
        day: 9,
        venue: "St. James' Park",
        city: "Newcastle upon Tyne",
        country: "England",
        time: "14:00",
        urlToEvent: "https://example.com/match/27",
        tba: false,
        minPrice: { gbp: 75, usd: 95, eur: 85, aud: 135, cad: 125, chf: 80 },
    },
    {
        homeTeam: "Manchester United",
        id: 28,
        categoryName: "Premier League",
        eventName: "Manchester United vs Wolverhampton Wanderers",
        year: 2025,
        month: "November",
        day: 22,
        venue: "Old Trafford",
        city: "Manchester",
        country: "England",
        time: "15:00",
        urlToEvent: "https://example.com/match/28",
        tba: false,
        minPrice: { gbp: 85, usd: 110, eur: 100, aud: 160, cad: 150, chf: 95 },
    },
    {
        homeTeam: "Arsenal",
        id: 29,
        categoryName: "Premier League",
        eventName: "Arsenal vs Burnley",
        year: 2025,
        month: "November",
        day: 23,
        venue: "Emirates Stadium",
        city: "London",
        country: "England",
        time: "14:00",
        urlToEvent: "https://example.com/match/29",
        tba: false,
        minPrice: { gbp: 75, usd: 95, eur: 85, aud: 135, cad: 125, chf: 80 },
    },
    {
        homeTeam: "Chelsea",
        id: 30,
        categoryName: "Premier League",
        eventName: "Chelsea vs Nottingham Forest",
        year: 2025,
        month: "November",
        day: 29,
        venue: "Stamford Bridge",
        city: "London",
        country: "England",
        time: "15:00",
        urlToEvent: "https://example.com/match/30",
        tba: false,
        minPrice: { gbp: 80, usd: 100, eur: 90, aud: 145, cad: 135, chf: 85 },
    },
    {
        homeTeam: "Liverpool",
        id: 31,
        categoryName: "Premier League",
        eventName: "Liverpool vs Sheffield United",
        year: 2025,
        month: "November",
        day: 30,
        venue: "Anfield",
        city: "Liverpool",
        country: "England",
        time: "14:00",
        urlToEvent: "https://example.com/match/31",
        tba: false,
        minPrice: { gbp: 85, usd: 110, eur: 100, aud: 160, cad: 150, chf: 95 },
    },
    {
        homeTeam: "Manchester City",
        id: 32,
        categoryName: "Premier League",
        eventName: "Manchester City vs Tottenham Hotspur",
        year: 2025,
        month: "December",
        day: 6,
        venue: "Etihad Stadium",
        city: "Manchester",
        country: "England",
        time: "17:30",
        urlToEvent: "https://example.com/match/32",
        tba: false,
        minPrice: { gbp: 100, usd: 125, eur: 115, aud: 180, cad: 170, chf: 110 },
    },
    {
        homeTeam: "Aston Villa",
        id: 33,
        categoryName: "Premier League",
        eventName: "Aston Villa vs Newcastle United",
        year: 2025,
        month: "December",
        day: 7,
        venue: "Villa Park",
        city: "Birmingham",
        country: "England",
        time: "16:00",
        urlToEvent: "https://example.com/match/33",
        tba: false,
        minPrice: { gbp: 80, usd: 100, eur: 90, aud: 145, cad: 135, chf: 85 },
    },
    {
        homeTeam: "Brighton & Hove Albion",
        id: 34,
        categoryName: "Premier League",
        eventName: "Brighton & Hove Albion vs Everton",
        year: 2025,
        month: "December",
        day: 13,
        venue: "Falmer Stadium",
        city: "Brighton",
        country: "England",
        time: "15:00",
        urlToEvent: "https://example.com/match/34",
        tba: false,
        minPrice: { gbp: 70, usd: 90, eur: 80, aud: 130, cad: 120, chf: 75 },
    },
    {
        homeTeam: "West Ham United",
        id: 35,
        categoryName: "Premier League",
        eventName: "West Ham United vs Leicester City",
        year: 2025,
        month: "December",
        day: 14,
        venue: "London Stadium",
        city: "London",
        country: "England",
        time: "14:00",
        urlToEvent: "https://example.com/match/35",
        tba: false,
        minPrice: { gbp: 75, usd: 95, eur: 85, aud: 135, cad: 125, chf: 80 },
    },
    {
        homeTeam: "Crystal Palace",
        id: 36,
        categoryName: "Premier League",
        eventName: "Crystal Palace vs Leeds United",
        year: 2025,
        month: "December",
        day: 20,
        venue: "Selhurst Park",
        city: "London",
        country: "England",
        time: "15:00",
        urlToEvent: "https://example.com/match/36",
        tba: false,
        minPrice: { gbp: 65, usd: 85, eur: 75, aud: 125, cad: 115, chf: 70 },
    },
    {
        homeTeam: "Fulham",
        id: 37,
        categoryName: "Premier League",
        eventName: "Fulham vs Southampton",
        year: 2025,
        month: "December",
        day: 21,
        venue: "Craven Cottage",
        city: "London",
        country: "England",
        time: "14:00",
        urlToEvent: "https://example.com/match/37",
        tba: false,
        minPrice: { gbp: 60, usd: 75, eur: 70, aud: 110, cad: 100, chf: 65 },
    },
    {
        homeTeam: "Manchester United",
        id: 38,
        categoryName: "Premier League",
        eventName: "Manchester United vs Liverpool",
        year: 2025,
        month: "December",
        day: 26,
        venue: "Old Trafford",
        city: "Manchester",
        country: "England",
        time: "17:30",
        urlToEvent: "https://example.com/match/38",
        tba: false,
        minPrice: { gbp: 120, usd: 150, eur: 140, aud: 220, cad: 200, chf: 135 },
    },
    {
        homeTeam: "Arsenal",
        id: 39,
        categoryName: "Premier League",
        eventName: "Arsenal vs Manchester City",
        year: 2025,
        month: "December",
        day: 28,
        venue: "Emirates Stadium",
        city: "London",
        country: "England",
        time: "16:00",
        urlToEvent: "https://example.com/match/39",
        tba: false,
        minPrice: { gbp: 110, usd: 140, eur: 130, aud: 200, cad: 190, chf: 120 },
    },
    {
        homeTeam: "Chelsea",
        id: 40,
        categoryName: "Premier League",
        eventName: "Chelsea vs Tottenham Hotspur",
        year: 2026,
        month: "January",
        day: 3,
        venue: "Stamford Bridge",
        city: "London",
        country: "England",
        time: "15:00",
        urlToEvent: "https://example.com/match/40",
        tba: false,
        minPrice: { gbp: 105, usd: 130, eur: 120, aud: 185, cad: 175, chf: 115 },
    },
    {
        homeTeam: "Liverpool",
        id: 41,
        categoryName: "Premier League",
        eventName: "Liverpool vs Newcastle United",
        year: 2026,
        month: "January",
        day: 4,
        venue: "Anfield",
        city: "Liverpool",
        country: "England",
        time: "14:00",
        urlToEvent: "https://example.com/match/41",
        tba: false,
        minPrice: { gbp: 100, usd: 125, eur: 115, aud: 180, cad: 170, chf: 110 },
    },
    {
        homeTeam: "Everton",
        id: 42,
        categoryName: "Premier League",
        eventName: "Everton vs Aston Villa",
        year: 2026,
        month: "January",
        day: 10,
        venue: "Goodison Park",
        city: "Liverpool",
        country: "England",
        time: "15:00",
        urlToEvent: "https://example.com/match/42",
        tba: false,
        minPrice: { gbp: 75, usd: 95, eur: 85, aud: 135, cad: 125, chf: 80 },
    },
    {
        homeTeam: "West Ham United",
        id: 43,
        categoryName: "Premier League",
        eventName: "West Ham United vs Brighton & Hove Albion",
        year: 2026,
        month: "January",
        day: 11,
        venue: "London Stadium",
        city: "London",
        country: "England",
        time: "14:00",
        urlToEvent: "https://example.com/match/43",
        tba: false,
        minPrice: { gbp: 70, usd: 90, eur: 80, aud: 130, cad: 120, chf: 75 },
    },
    {
        homeTeam: "Crystal Palace",
        id: 44,
        categoryName: "Premier League",
        eventName: "Crystal Palace vs Fulham",
        year: 2026,
        month: "January",
        day: 17,
        venue: "Selhurst Park",
        city: "London",
        country: "England",
        time: "15:00",
        urlToEvent: "https://example.com/match/44",
        tba: false,
        minPrice: { gbp: 65, usd: 85, eur: 75, aud: 125, cad: 115, chf: 70 },
    },
    {
        homeTeam: "Leicester City",
        id: 45,
        categoryName: "Premier League",
        eventName: "Leicester City vs Southampton",
        year: 2026,
        month: "January",
        day: 18,
        venue: "King Power Stadium",
        city: "Leicester",
        country: "England",
        time: "14:00",
        urlToEvent: "https://example.com/match/45",
        tba: false,
        minPrice: { gbp: 60, usd: 75, eur: 70, aud: 110, cad: 100, chf: 65 },
    },
    {
        homeTeam: "Manchester United",
        id: 46,
        categoryName: "Premier League",
        eventName: "Manchester United vs Burnley",
        year: 2026,
        month: "February",
        day: 7,
        venue: "Old Trafford",
        city: "Manchester",
        country: "England",
        time: "15:00",
        urlToEvent: "https://example.com/match/46",
        tba: false,
        minPrice: { gbp: 80, usd: 100, eur: 90, aud: 145, cad: 135, chf: 85 },
    },
    {
        homeTeam: "Arsenal",
        id: 47,
        categoryName: "Premier League",
        eventName: "Arsenal vs Nottingham Forest",
        year: 2026,
        month: "February",
        day: 8,
        venue: "Emirates Stadium",
        city: "London",
        country: "England",
        time: "14:00",
        urlToEvent: "https://example.com/match/47",
        tba: false,
        minPrice: { gbp: 75, usd: 95, eur: 85, aud: 135, cad: 125, chf: 80 },
    },
    {
        homeTeam: "Chelsea",
        id: 48,
        categoryName: "Premier League",
        eventName: "Chelsea vs Sheffield United",
        year: 2026,
        month: "February",
        day: 14,
        venue: "Stamford Bridge",
        city: "London",
        country: "England",
        time: "15:00",
        urlToEvent: "https://example.com/match/48",
        tba: false,
        minPrice: { gbp: 70, usd: 90, eur: 80, aud: 130, cad: 120, chf: 75 },
    },
    {
        homeTeam: "Liverpool",
        id: 49,
        categoryName: "Premier League",
        eventName: "Liverpool vs Wolverhampton Wanderers",
        year: 2026,
        month: "February",
        day: 15,
        venue: "Anfield",
        city: "Liverpool",
        country: "England",
        time: "14:00",
        urlToEvent: "https://example.com/match/49",
        tba: false,
        minPrice: { gbp: 85, usd: 110, eur: 100, aud: 160, cad: 150, chf: 95 },
    },
    {
        homeTeam: "Manchester City",
        id: 50,
        categoryName: "Premier League",
        eventName: "Manchester City vs Aston Villa",
        year: 2026,
        month: "March",
        day: 1,
        venue: "Etihad Stadium",
        city: "Manchester",
        country: "England",
        time: "17:30",
        urlToEvent: "https://example.com/match/50",
        tba: false,
        minPrice: { gbp: 95, usd: 120, eur: 110, aud: 170, cad: 160, chf: 105 },
    },

    {
        homeTeam: "Bournemouth",
        id: 51,
        categoryName: "Premier League",
        eventName: "Bournemouth vs Everton",
        year: 2026,
        month: "March",
        day: 3,
        venue: "Vitality Stadium",
        city: "Bournemouth",
        country: "England",
        time: "15:00",
        urlToEvent: "https://example.com/match/50",
        tba: false,
        minPrice: { gbp: 95, usd: 120, eur: 110, aud: 170, cad: 160, chf: 105 },
    },
    {
        homeTeam: "Manchester City",
        id: 52,
        categoryName: "Premier League",
        eventName: "Brentford vs Manchester City",
        year: 2026,
        month: "March",
        day: 30,
        venue: "Gtech Community Stadium",
        city: "Brentford – The Town",
        country: "England",
        time: "17:00",
        urlToEvent: "https://example.com/match/50",
        tba: false,
        minPrice: { gbp: 95, usd: 120, eur: 110, aud: 170, cad: 160, chf: 105 },
    },
];





